server:
  port: ":8080"  # 服务器端口

data:
  db_path: "internal/data/voice_assistant.db"

llm:
  api_key: "${DASHSCOPE_API_KEY}"  # 从环境变量读取API密钥（推荐）
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"  # 通义千问兼容接口地址
  model_name: "qwen-plus"  # 模型名称（可替换为qwen-turbo等）
  max_tokens: 2048  # 最大生成 tokens
  temperature: 0.7  # 温度参数（0-1）
  timeout_sec: 60  # 接口超时时间